---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-approver-policy
  namespace: default
data:
  example.rego: |
    package approval

    
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-selfsigned-cert
spec:
  commonName: my-selfsigned.invalid
  secretName: my-selfsigned-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
